name: 3D Ribbons
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # æ¯å¤©è‡ªåŠ¨æ›´æ–°
  workflow_dispatch:  # æ”¯æŒæ‰‹åŠ¨è§¦å‘
permissions:
  contents: write  # å…è®¸Actions pushæ–‡ä»¶
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 3D Ribbon
      uses: yoshi389111/github-profile-3d-contrib@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DETAILED: "true"
        SHEET: "1"
        SHEET2: "2"
        SHEET3: "3"
        MANUFACTURER: "LEGO"
        DISPLAY_HEADING_LABEL: "Don't forget to star ğŸŒŸ"
        REPO: "codeInbpm/codeInbpm"  # ä½ çš„ä»“åº“
        CATEGORIES: "â­ Emoji:1 | ğŸ’¬ Pull Requests:2 | ğŸ“– Wiki:3 | ğŸ“ Issues:4 | âœ… Merged Pull Requests:5 | ğŸ“„ Releases:6 | ğŸ¢ Organization:7 | ğŸ‘¥ People:8 | ğŸ† Trophies:9 | ğŸ¯ Achievements:10"
    - name: Commit & Push
      run: |
        git config user.email action@github.com
        git config username github-actions
        git add .
        git commit -m "Update 3D contrib" || echo "No changes"
        git push
